[project]
name = "These-pancreas"
r_version = "4.5"

repositories = [
    {alias = "CRAN", url = "https://packagemanager.posit.co/cran/latest"},
]

dependencies = [
    { name = "ggswim", git = "https://github.com/CHOP-CGTInformatics/ggswim", branch = "main" },
    { name = "hebstr", path = "/home/julien/Documents/packages/R-hebstr" },
    # { name = "hebstr", git = "https://github.com/hebstr/hebstr", branch = "main" },
    "tidyverse",
    "googlesheets4",
    "labelled",
    "gtsummary",
    "httpuv",
    "conflicted",
    "fs",
    "here",
    "ggsurvfit",
    "ggrepel",
    "Gmisc",
    "grid",
    "gridtext",
    "rvg",
    "officer",
    "tidycmprsk",
    "performance",
    "logistf",
    "brglm2",
    "detectseparation",
    "magick",
    "sessioninfo",
]
