[project]
name = "These-pancreas"
r_version = "4.6"

repositories = [
  { alias = "CRAN", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
  { name = "hebstr", path = "/home/julien/Documents/packages/R-hebstr" },
  # { name = "hebstr", git = "https://github.com/hebstr/hebstr", branch = "main" },
  "tidyverse",
  "googlesheets4",
  "labelled",
  "gtsummary",
  "conflicted",
  "fs",
  "ggsurvfit",
  "ggrepel",
  "Gmisc",
  "grid",
  "gt",
  "rvg",
  "performance",
  "sessioninfo",
  "rlang",
  "broom",
  "survival",
  "patchwork",
  "car",
  "cli",
  "openxlsx2",
  "knitr",
  "svglite",
  "systemfonts",
  "xfun",
  "yaml12",
]
